version: "3.9"
services:
  myapirest:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - postgresql
      - redis
    volumes:
      - .:/home/app
  postgresql:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql:/bitnami/postgresql
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
volumes:
  postgresql: