version: "3.9"
services:
  myapirest:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgresql
      - redis
  postgresql:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    